name: Deploy React app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (prefer ci, fallback to install)
        run: |
          if [ -f package-lock.json ]; then
            echo "Lockfile found → trying npm ci"
            npm ci || (echo "npm ci failed (lock mismatch). Falling back to npm install…" && npm install --no-audit --no-fund)
          else
            echo "No package-lock.json → npm install"
            npm install --no-audit --no-fund
          fi

      - name: Build
        env:
          CI: true
        run: npm run build

      - name: Detect build directory (Vite=dist / CRA=build)
        run: |
          if [ -d dist ]; then
            echo "BUILD_DIR=dist" >> $GITHUB_ENV
          elif [ -d build ]; then
            echo "BUILD_DIR=build" >> $GITHUB_ENV
          else
            echo "No build output folder found (dist/build)."
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
